name:                HsWiki
version:             0.1.0.0
github:              "thma/HsWiki"
license:             BSD3
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2021 Thomas Mahler"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thma/HsWiki#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-html
- yesod
- text
- directory
- cmdargs
- cmark-gfm
- extra


executables:
  HsWiki:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
