-- typical local development
 Development:
   host: localhost
   port: 3000
   contentDir: content

   -- ssl: will default false
   -- approot: will default to "http://localhost:3000"
 -- typical outward-facing production box
 Production:
   host: www.example.com

   -- ssl: will default false
   -- port: will default 80
   -- approot: will default "http://www.example.com"
 -- maybe you're reverse proxying connections to the running app
 -- on some other port
 Production:
   port: 8080
   approot: "http://example.com"

 -- approot is specified so that the non-80 port is not appended
 -- automatically.